[package]
name = "DuckStudio"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "^2.0.0-alpha", features = [] }

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
arrow = { version = "47.0.0", features = ["prettyprint"] }

duckdb = { version = "0.9.1", features = [
    "modern-full",
    "bundled"
] }


tauri = { version = "^2.0.0-alpha", features = [
    "devtools",
    "icon-ico",
    "icon-png",
    "tray-icon",
] }
# tauri plugin
tauri-plugin-shell = "2.0.0-alpha"
tauri-plugin-dialog = "2.0.0-alpha"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
